<?php 
if(!empty($this->dados)):

	foreach($this->dados as $item): ?>
<img src='<?php echo $item['url']; ?>' style='padding:3px;' /><a href=javascript:callAjax('<?php echo $this->url("meus-anuncios",array('action'=>'deleteimage','id'=>$this->id_anuncio,'cod'=>$item['nome'])); ?>',$('#loadfotos<?php echo $this->id_anuncio; ?>'));  ><i class='icon-remove-circle'></i></a>

<?php endforeach; 
endif;
?>
