      <script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
      <script type="text/javascript">
      
      	tinyMCE.init({
		    mode : "textareas",
		    theme : "advanced",
		    theme_advanced_buttons1 :"mybutton,bold,italic,underline,separator,justifyleft,justifycenter,justifyright,justifyfull",
		    content_css : "css/bootstrap.css",
			theme_advanced_buttons2 : "",
		    theme_advanced_buttons3 : "",
		    theme_advanced_toolbar_location : "top",
		    theme_advanced_toolbar_align : "left",
		    theme_advanced_statusbar_location : "bottom",
		    plugins : 'inlinepopups'/*,
		    setup : function(ed) {
		        // Add a custom button
		        ed.addButton('mybutton', {
		            title : 'My button',
		            image : 'img/example.gif',
		            onclick : function() {
		                // Add you own code to execute something on click
		                ed.focus();
		                ed.selection.setContent('Hello world!');
		            }
		        });
		    }*/
		});
		
		
	</script>

	<style type="text/css">
	.control-label{
		text-align: left !important;
		width: 70px !important;
	}

	.controls {
		margin-left: 75px !important;
	}
	</style>

      <!-- Example row of columns -->
      <div class="row">
      
        <div class="span7">
          <ul class="breadcrumb">
			  <li><a href="/">Home</a> <span class="divider">/</span></li>
			  <li class="active">Meus Anúncios</li>
			</ul>
          	<button class="btn btn-mini" type="button" id="btn_filtrar" onclick="displayDivDinamic($('#div_filtra'));">Filtrar</button> <small><a href="<?php echo $this->url('home',array('username'=>$this->username)); ?>"><i class="icon-user"></i> <?php echo $this->username; ?></a></small>
            <div id='div_filtra'>
            <small >
              <table class="">
                <tr>
                  <td>
                    <ul>
                      <li>Id <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'id','type_order'=>'ASC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-ascending.png" alt="descending, gtk, sort icon"></a> <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'id','type_order'=>'DESC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                      <li>Título <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'titulo','type_order'=>'ASC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'titulo','type_order'=>'DESC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                      <li>Status <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'status','type_order'=>'ASC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'status','type_order'=>'DESC')); ?>",$("#load-meus-anuncios-list"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                    </ul>
                  </td>
                </tr>
              </table>
            </small>
          </div>
			<div id="load-meus-anuncios-list">
			</div>
       </div>
        <div class="span5">
        	
       	  <?php if($this->qtd_anuncio > 0 || $this->action == 'edit'){ ?>

       	  	  <?php if($this->action != 'edit'){ ?>

	          <p>Você pode cadastrar <?php echo $this->qtd_anuncio; ?> anúncio(s).</p>
			
			  <?php } ?>
	

	          <h4><?php $form = $this->form; if($form->get('id')->getValue()) echo "Editar"; else echo "Novo"; ?> Anúncio #<?php echo $form->get('id')->getValue(); ?></h4>
	           <?php 
	           
	           if($this->msg['tipo'] == "error"){
	           		echo '<div class="alert alert-error">';
					switch ($this->msg['cod_msg']) {
						case '1':
							echo "Usuário ou senha inválidos";
							break;
						
						default:
							
							break;
					}
					echo '</div>';
				
	           }elseif($this->msg['tipo'] == "success"){
	           		echo '<div class="alert alert-success">';
					switch ($this->msg['cod_msg']) {
						case '1':
							echo "Anúncio cadastrado com sucesso";
							break;
							
						case '2':
							echo "Anúncio atualizado com sucesso";
							break;
						
						default:
							
							break;
					}
					echo '</div>';
	           }
	           
	           ?>
	           
			  
			  <?php            
				 $action = $form->get('id')->getValue() ? "edit" : "index" ;
				 //$form->setAttribute('action', $this->url('admin/servico',array('action'=>$action)));
				 $form->setAttribute('class', 'form-horizontal');
				 $form->prepare();
				 echo $this->form()->openTag($form) . PHP_EOL;
				 echo $this->formInput($form->get('id'));
				 echo $this->formInput($form->get('id_usuario'));
				?>
	            <div class="control-group ">
				    <label class="control-label" for="">Título</label>
				    <div class="controls">
				      <?php echo $this->formInput($form->get('titulo')); ?>
				      <?php echo $this->formElementErrors($form->get('titulo')); ?>
				    </div>
				  </div>
				  <p>
				  <small>Para descrição do anúncio, recomendamos informar dados como email, telefone entre outros.</small>
				  </p>
				  <div class="control-group">
				    <label class="control-label" for="">Descrição</label>
				    <div class="controls">
				      <?php echo $this->formTextarea($form->get('descricao')); ?>
				      <?php echo $this->formElementErrors($form->get('descricao')); ?>
				    </div>
				  </div>
				  
				  <div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn"><?php if($form->get('id')->getValue()) echo "Editar"; else echo "Cadastrar"; ?></button> 
				      <?php if($form->get('id')->getValue()): ?> <a href="<?php echo $this->url('meus-anuncios'); ?>">Novo Anúncio</a><?php endif; ?>
				    </div>
				  </div>
				</form>
			<?php } ?>
			<p>(0) Convites enviados - (0) Amigos Cadastrados</p>
			<p>Para cadastrar <b>novos anúncios</b> envie convites para seus amigos. </p>
			<div id="loadconvite"></div>
          
        </div>
      </div>
      <script type="text/javascript">
      

      	
		 !function ($) {
		
		     $(function(){
		     		$('#div_filtra').hide();
		     		callAjax("<?php echo $this->url('convite'); ?>",$('#loadconvite'));
		     		callAjax("<?php echo $this->url('meus-anuncios-list',array('col_order'=>'id','type_order'=>'desc')); ?>",$('#load-meus-anuncios-list'));
		
				    
		
		    })
		
		}(window.jQuery)
		

		

      </script>





