
          
<table class="table">
  <thead>
    <tr>
      
      <th>Título</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  	<?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
    <tr>
     
      <td width="95%"><a href="<?php echo $this->url("home",array("username"=>$this->username,"action"=>'a',"id_ads"=>$value->id,"url_ads"=>$value->url)); ?>" data-toggle="tooltip" data-original-title="Visualizar Anúncio"><?php echo $value->titulo; ?></a></td>
      <td>
      <?php
      	switch ($value->status) {
      		case '0':
      			$src= "/img/status/status_mod.png";
      			$txt_tooltip= "Moderação";
      			break;

      		case '1':
      			$src= "/img/status/status_ok.png";
      			$txt_tooltip= "Ativo";
      			break;
      		
      		case '2':
      			$src= "/img/status/status_rep.png";
      			$txt_tooltip= "Reprovado";
      			break;		
      		
      		default:
      			# code...
      			break;
      	}
      ?>
       <a href="#" data-toggle="tooltip" data-placement="top" data-original-title="No momento este anúncio está em <?php echo $txt_tooltip; ?>"><img src="<?php echo $src; ?>" /></a>
   	  </td>
      
    </tr>
    <tr>
    	<td colspan="2">
    		<table class="table table-condensed table-bordered">
           <tr>
              <td colspan="4">
                <a href="<?php echo $this->url("meus-anuncios",array('action'=>'edit','id'=>$value->id)); ?>"><i class="icon-edit"></i> Editar</a> <a href="<?php echo $this->url("meus-anuncios",array('action'=>'delete','id'=>$value->id)); ?>"><i class="icon-remove-circle"></i> Excluir</a>
              </td>
            </tr>
            <tr>
            	<td colspan="4">
            		<div class="alert alert-error hide">
			            <button type="button" class="close" data-dismiss="alert">×</button>
			            <span></span>
			          </div>
            	</td>
            </tr>
            <tr>
            	
            	<td>
            		<form class="fileupload" action="<?php echo $this->url("meus-anuncios",array('action'=>'addimage','id'=>$value->id)); ?>" method="POST" enctype="multipart/form-data">
                		<span class="label label-important"></span>
                		<span class="btn btn-success fileinput-button" >
		                    <i class="icon-plus icon-white"></i>
		                    <span>Adicionar fotos</span>
		                    <input type="file" name="filesaddfotos" multiple="">
		                </span>
		                <span class="loading"></span>
            		</form>
            	</td>
            	<td colspan="2">
            		<a href="<?php echo $this->url("perguntas",array('id_ads'=>$value->id)); ?>" class="btn btn-info"><i class="icon-list icon-white"></i> Perguntas</a>
            	</td>
            		
            </tr>
            <tr>
            	
            	<td  width="" colspan="4">
                <div id="loadfotos<?php echo $value->id; ?>" style="overflow:auto;width:100%;max-height:60px;">
            		<script>callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage','id'=>$value->id)); ?>",$('#loadfotos<?php echo $value->id; ?>'));</script>
            	   </div>
              </td>
            		
            </tr>
   			</table>
   </td>
  </tr>
 
    <?php } }else{ ?>
    <tr>
    	<td colspan="4">Nenhum anúncio cadastro</td>
    </tr>
    
    <?php } ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>
<script type="text/javascript">

		 !function ($) {
		
		     $(function(){

              // tooltip demo
              $('.table').tooltip({
                selector: "a[data-toggle=tooltip]"
              })

		     		//callAjax("<?php echo $this->url('convite'); ?>",$('#loadconvite'));
					
				    $('.fileupload').fileupload({
				        // Uncomment the following to send cross-domain cookies:
				        //xhrFields: {withCredentials: true},
				        url: $(this).attr('action'),
				        autoupload: true,
				        add: function (e, data) {
				        	//console.dir(data);
				        	//console.dir(data.files);
				        	var valid = true;
	                        var re = /^.+\.((jpg)|(png)|(gif)|(jpeg))$/i;
	                        var form_current = $(this); 
	                        
	                        form_current.find('.loading').html("<img src='/img/loading/loading.gif' />");
				            
	                        $.each(data.files, function (index, file) {
	                        	if (!re.test(file.name)) {
	                            	form_current.find('.loading').html("");
			                        $('.alert').find('span').html('This file type is not supported');
			                        $('.alert').show();
	                                valid = false;
	                            }
	                        });
	                        if (valid)
	                            data.submit();
				        	
				        },
	                    done: function (e, data) {
	                    	var obj = JSON.parse(data.result);
	                        $(this).find('.loading').html("");
	                        if(obj.files.error != undefined){
	                        	
	                        	$('.alert').find('span').html(obj.files.error);
	                        	$('.alert').show();
	                        	//$('.alert').alert();
	                        }else{
	                        	callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage')); ?>/"+obj.files[0].id,$('#loadfotos'+obj.files[0].id));
	                        }	
	                        
	                    },
	                    error: function () {
	                        $(this).find('.label-important').html('An error occured while uploading the document.');
	                    }
				    });
		
		    })
		
		}(window.jQuery)

</script>





