
          
<table class="table">
  <thead>
    <tr>
      
      <th>Título</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  	<?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
    <tr>
     
      <td width="95%"><a href="<?php echo $this->url("home",array("username"=>$this->username,"action"=>'a',"id_ads"=>$value['a_id'],"url_ads"=>$value['a_url'])); ?>" data-toggle="tooltip" data-original-title="Visualizar Anúncio"><i class="icon-eye-open"></i> <?php echo $value['a_titulo']; ?></a></td>
      <td>
      <?php
      	switch ($value['a_status']) {
      		case '0':
      			$src= "/img/status/status_mod.png";
      			$txt_tooltip= "Moderação";
      			break;

      		case '1':
      			$src= "/img/status/status_ok.png";
      			$txt_tooltip= "Ativo";
      			break;
      		
      		case '2':
      			$src= "/img/status/status_rep.png";
      			$txt_tooltip= "Reprovado";
      			break;		
      		
      		default:
      			# code...
      			break;
      	}
      ?>
       <a href="#" data-toggle="tooltip" data-placement="top" data-original-title="No momento este anúncio está em <?php echo $txt_tooltip; ?>"><img src="<?php echo $src; ?>" /></a>
   	  </td>
      
    </tr>
    <tr>
    	<td colspan="2">
    		<table class="table table-condensed table-bordered">
           <tr>
              <td colspan="4">
                <a href="<?php echo $this->url("meus-anuncios",array('action'=>'edit','id'=>$value['a_id'])); ?>"><i class="icon-edit"></i> Editar</a> <a href="<?php echo $this->url("meus-anuncios",array('action'=>'delete','id'=>$value['a_id'])); ?>"><i class="icon-remove-circle"></i> Excluir</a>
              </td>
            </tr>
            <tr>
            	<td colspan="4">
            		<div class="alert alert-error hide">
			            <button type="button" class="close" data-dismiss="alert">×</button>
			            <span></span>
			          </div>
            	</td>
            </tr>
            <tr>
            	
            	<td>
            		<form class="fileupload" action="<?php echo $this->url("meus-anuncios",array('action'=>'addimage','id'=>$value['a_id'])); ?>" method="POST" enctype="multipart/form-data">
                		<span class="label label-important"></span>
                		<span class="btn btn-success fileinput-button" >
		                    <i class="icon-plus icon-white"></i>
		                    <span>Adicionar fotos</span>
		                    <input type="file" name="filesaddfotos" multiple="">
		                </span>
		                <span class="loading"></span>
            		</form>
            	</td>
            	<td colspan="2">
            		<a href="<?php echo $this->url("perguntas",array('id_ads'=>$value['a_id'])); ?>" class="btn btn-info"><i class="icon-list icon-white"></i> Perguntas</a>
            	</td>
            		
            </tr>
            <tr>
            	
            	<td  width="" colspan="4">
                <div id="loadfotos<?php echo $value['a_id']; ?>" style="overflow:auto;width:100%;max-height:60px;">
            		<script>callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage','id'=>$value['a_id'])); ?>",$('#loadfotos<?php echo $value['a_id']; ?>'));</script>
            	   </div>
              </td>
            		
            </tr>
            <tr>
              <td colspan="4">
                <table>
                  <tr>
                    <td width="12%"><img src="/img/servicos/perifericos60x60.png" /></td>
                    <td>
                        <?php switch($value['pa_status']){

                            case 0:
                                ?> <small>Consultoria Adwords</small> <br> Em análise <img src="/img/status/status_mod.png" /><br> Aguarde a ativação da campanha. <?php
                                break;

                            case 1:
                                ?> <small>Consultoria Adwords</small> <br> Campanha Ativa <img src="/img/status/status_ok.png" /><br> Aguarde a conclusão desta campanha para exibição dos resultados  <?php
                                break;

                            case 2:

                                ?> <small>Consultoria Adwords</small> <br> Campanha Finalizada <img src="/img/status/status_rep.png" /> <a href="<?php echo $this->url("servico-app",array('action'=>'adwords','id_anuncio'=>$value['a_id'])); ?>">[ Reativar ]</a><br>
                        <small>
                                <table>
                                    <tr>
                                        <td>
                                            Iniciando em:
                                        </td>
                                        <td>
                                            <?php echo $value['pa_data_inicio']->format('d/m/Y'); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Finalizado em:
                                        </td>
                                        <td>
                                            <?php echo $value['pa_data_fim']->format('d/m/Y'); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Média de Click Únicos:
                                        </td>
                                        <td>
                                            <?php echo $value['pa_media_clique']; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Posição média:
                                        </td>
                                        <td>
                                            <?php echo $value['pa_posicao_media']; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Impressões:
                                        </td>
                                        <td>
                                            <?php echo $value['pa_impressao']; ?>
                                        </td>
                                    </tr>
                                 </table></small>
                                 <?php
                                break;


                             default:

                                ?>
                                    <div style="overflow:auto;width:100%;max-height:70px;">
                                        <small>Você sabia que entre anúncios e sites publicados no serviço <b>Google AdWords</b> (Links patrocinados do google) tem mas chances de serem clicados sobre outros anúncios exibidos no buscador do google? <br>Para atender suas necessidades como anunciante, oferecemos um serviço de divulgação diferenciado com consultores especializados em analizar e otimizar seus anúncios. Com objetivo de publicar entre os 7 primeiros resultados na busca efetuada pelos usuários no buscador google.</small></div><br>
                                    <a href="<?php echo $this->url("servico-app",array('action'=>'adwords','id_anuncio'=>$value['a_id'])); ?>"><i class="icon-globe"></i> Clique aqui e saiba mais como ativar sua campanha no google</a>

                                <?php
                        }
                        ?>


                    </td>
                  </tr>
                </table>
                 
              </td>
            </tr>

   			</table>
   </td>
  </tr>
 
    <?php } }else{ ?>
    <tr>
    	<td colspan="4">Nenhum anúncio cadastro</td>
    </tr>
    
    <?php } ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>
<script type="text/javascript">

		 !function ($) {
		
		     $(function(){

              // tooltip demo
              $('.table').tooltip({
                selector: "a[data-toggle=tooltip]"
              })

		     		//callAjax("<?php echo $this->url('convite'); ?>",$('#loadconvite'));
					
				    $('.fileupload').fileupload({
				        // Uncomment the following to send cross-domain cookies:
				        //xhrFields: {withCredentials: true},
				        url: $(this).attr('action'),
				        autoupload: true,
				        add: function (e, data) {
				        	//console.dir(data);
				        	//console.dir(data.files);
				        	var valid = true;
	                        var re = /^.+\.((jpg)|(png)|(gif)|(jpeg))$/i;
	                        var form_current = $(this); 
	                        
	                        form_current.find('.loading').html("<img src='/img/loading/loading.gif' />");
				            
	                        $.each(data.files, function (index, file) {
	                        	if (!re.test(file.name)) {
	                            	form_current.find('.loading').html("");
			                        $('.alert').find('span').html('This file type is not supported');
			                        $('.alert').show();
	                                valid = false;
	                            }
	                        });
	                        if (valid)
	                            data.submit();
				        	
				        },
	                    done: function (e, data) {
	                    	var obj = JSON.parse(data.result);
	                        $(this).find('.loading').html("");
	                        if(obj.files.error != undefined){
	                        	
	                        	$('.alert').find('span').html(obj.files.error);
	                        	$('.alert').show();
	                        	//$('.alert').alert();
	                        }else{
	                        	callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage')); ?>/"+obj.files[0].id,$('#loadfotos'+obj.files[0].id));
	                        }	
	                        
	                    },
	                    error: function () {
	                        $(this).find('.label-important').html('An error occured while uploading the document.');
	                    }
				    });
		
		    })
		
		}(window.jQuery)

</script>





