<div class="row">
      
        
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li class="active">Conta</li>
          </ul>
                <div class="span4">        
            <?php

           if($this->msg['tipo'] == "error"){
                echo '<div class="alert alert-error">';
                switch ($this->msg['cod_msg']) {
                    case '1':
                        echo "";
                        break;
                    
                    default:
                        
                        break;
                }
                echo '</div>';
            
           }elseif($this->msg['tipo'] == "success"){
                echo '<div class="alert alert-success">';
                switch ($this->msg['cod_msg']) {
                    case '1':
                        echo "Dados Alterado com sucesso";
                        break;
                        
                    case '2':
                        echo "";
                        break;
                    
                    default:
                        
                        break;
                }
                echo '</div>';
           }


           ?>
           
           <?php

             $form = $this->form;
             $form->setAttribute('action', $this->url('conta'));
             $form->prepare();
             echo $this->form()->openTag($form) . PHP_EOL;
            ?>


            <div class="control-group ">
                <label class="control-label" for="inputEmail">Nome</label>
                <div class="controls">
                  <?php echo $this->formInput($form->get('nome')); ?>
                  <?php echo $this->formElementErrors($form->get('nome')); ?>
                </div>
              </div>
 
              <div class="control-group">
                <div class="controls">
                  <button type="submit" class="btn">Alterar</button>
                </div>
              </div>
            </form>
        </div>
   
</div>
