<div class="row">
      
        <div class="span7">
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li class="active">Meus anúncios</li>
          </ul>


          <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Pergunta</th>
                  <th>Status</th>
                  <th>Ações</th>
                </tr>
              </thead>
              <tbody>
                <?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
                <tr>
                  <td><?php echo $value->id; ?></td>
                  <td><?php echo substr($value->msg_pergunta, 0, 40); ?></td>
                  <td>

                  
                  <?php
                    switch ($value->status) {
                      case '0':
                        $src= "/img/status/status_mod.png";
                        $txt_tooltip= "Aguardando resposta";
                        break;

                      case '1':
                        $src= "/img/status/status_ok.png";
                        $txt_tooltip= "Publicada";
                        break;
                      
                      case '2':
                        $src= "/img/status/status_rep.png";
                        $txt_tooltip= "Removida do anúncio";
                        break;    
                      
                      default:
                        # code...
                        break;
                    }
                  ?>
                   <a href="#" data-toggle="tooltip" data-placement="top" data-original-title="No momento esta pergunta está <?php echo $txt_tooltip; ?>"><img src="<?php echo $src; ?>" /></a>
                  </td>
                  <td>
                   <a href='javascript:callAjax("<?php echo $this->url('reposta-pergunta',array('id_pergunta'=>$value->id)); ?>",$("#load-pergunta"));' > Responder </a>
                  </td>
                </tr>
                <?php } }else{ ?>
                <tr>
                  <td colspan="4">Nenhum pergunta enviada</td>
                </tr>
                
                <?php } ?>
                  </tbody>
            </table>
        </div>

        <div class="span5" id="load-pergunta">    

        </div>
   
</div>

<script type="text/javascript">
  
!function ($) {

   $(function(){

      //callAjax("<?php echo $this->url('reposta-pergunta',array('id_ads'=>$this->dados['id_anuncio'])); ?>",$('#load-pergunta'));

    })

}(window.jQuery)




</script>
