<?php 
               
if($this->msg['tipo'] == "error"){
    echo '<div class="alert alert-error">';
    switch ($this->msg['cod_msg']) {
        case '1':
            echo "Usuário ou senha inválidos";
            break;
        
        default:
            
            break;
    }
    echo '</div>';

}elseif($this->msg['tipo'] == "success"){
    echo '<div class="alert alert-success">';
    switch ($this->msg['cod_msg']) {
        case '1':
            echo "Pergunta respondida e publicada com sucesso";
            break;
            
        case '2':
            echo "Pergunta atualizada e publicada com sucesso";
            break;
        
        default:
            
            break;
    }
    echo '</div>';

    ?>
    <small>Dica: Para remover a pergunta do anúncio, clique em retirar.</small>

    <?php


}else{

?>
<?php
 $form = $this->form;            
 //$action = $form->get('id')->getValue() ? "edit" : "index" ;
 //$form->setAttribute('action', $this->url('admin/servico',array('action'=>$action)));
 $form->setAttribute('class', 'form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form) . PHP_EOL;

?>
  <fieldset>
    <legend><i class="icon-list"></i> Responder</legend>
    <p>
        <label>Pergunta</label>
        <span class="help-block"><?php echo $this->dados[0]->msg_pergunta ?></span>
    </p>
    <p>
        <label>Mensagem</label>
        <?php echo $this->formTextarea($form->get('msg_resposta')); ?>
        <?php echo $this->formElementErrors($form->get('msg_resposta')); ?>
    </p>    
    <p>
    <?php if($this->tipo == 1): ?>
    <button type="button" class="btn" onclick="callAjax('<?php echo $this->url('reposta-pergunta',array('id_pergunta'=>$this->dados[0]->id,'tipo'=>$this->tipo)); ?>',$('#load-pergunta'),'POST','msg_resposta='+$('#respostapergunta').find('textarea[name=msg_resposta]').val(),'<?php echo $this->url('perguntas',array('id_ads'=>$this->dados[0]->id_anuncio,'action'=>'listaperguntaconteudo')); ?>',$('#load-list-pergunta'));">Editar</button>
    <?php else: ?>
    <button type="button" class="btn" onclick="callAjax('<?php echo $this->url('reposta-pergunta',array('id_pergunta'=>$this->dados[0]->id)); ?>',$('#load-pergunta'),'POST','msg_resposta='+$('#respostapergunta').find('textarea[name=msg_resposta]').val(),'<?php echo $this->url('perguntas',array('id_ads'=>$this->dados[0]->id_anuncio,'action'=>'listaperguntaconteudo')); ?>',$('#load-list-pergunta'));">Enviar</button>

    <?php endif; ?>
    </p>
    
  </fieldset>
</form>

<?php } ?>

