<!-- Example row of columns -->
<div class="row">

<div class="span7">
  <ul class="breadcrumb">
	  <li><a href="/">Home</a> <span class="divider">/</span></li>
	  <li class="active">Busca</li>
	</ul>
  <p>
    Procurando por <b>"<?php echo $this->dados['word']; ?>"</b>
  </p>
  <p>
  	<button class="btn btn-mini" type="button" id="btn_filtrar" onclick="displayDivDinamic($('#div_filtra'));">Filtrar</button> 
    <div id='div_filtra'>
    <small >
      <table class="">
        <tr>
          <td>
            <ul>
              <li>Cadastro <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'id','type_order'=>'ASC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-ascending.png" alt="descending, gtk, sort icon"></a> <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'id','type_order'=>'DESC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
              <li>Título <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'titulo','type_order'=>'ASC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'titulo','type_order'=>'DESC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
              <li>Descrição <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'descricao','type_order'=>'ASC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'descricao','type_order'=>'DESC')); ?>",$("#load-listsearch"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
            </ul>
          </td>
        </tr>
      </table>
    </small>
  </div>
</p>
	<div id="load-listsearch">
	</div>
</div>

</div>
<script type="text/javascript">


	
 !function ($) {

     $(function(){
     		$('#div_filtra').hide();
     		//callAjax("<?php echo $this->url('convite'); ?>",$('#loadconvite'));
     		callAjax("<?php echo $this->url('list-search',array('word'=>$this->dados['word'],'col_order'=>'id','type_order'=>'desc')); ?>",$('#load-listsearch'));

		    

    })

}(window.jQuery)




</script>





