<h4>Informe sua nova senha</h4>
        <p>Preencha os campos abaixo e clique no botão alterar para renovar a sua senha de acesso.</p>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
//echo $this->formHidden($form->get('id')) . PHP_EOL;
?>

<div class="control-group ">
	<label class="control-label" for="inputEmail">Nova Senha*</label>
	<div class="controls">
	  <?php echo $this->formInput($form->get('senha')); ?>
	  <?php echo $this->formElementErrors($form->get('senha')); ?>
	</div>
</div>


<div class="control-group ">
	<label class="control-label" for="inputEmail">Confirme sua senha*</label>
	<div class="controls">
	  <?php echo $this->formInput($form->get('contra_senha')); ?>
	  <?php echo $this->formElementErrors($form->get('contra_senha')); ?>
	</div>
</div>

<div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Cadastrar</button> 
    </div>
  </div>
</form>


