<div background="<?php echo $this->serverUrl('/img/texture/greyBackgroundTexture-v1.jpg'); ?>">
        <table width="100%" cellpadding="0" cellspacing="0">
            <tbody><tr>
                <td style="padding-left:50px;padding-right:50px" background="<?php echo $this->serverUrl('/img/texture/greyBackgroundTexture-v1.jpg'); ?>">
                    <table align="center" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td align="center" style="width:540px">
                                <table align="center" width="100%" cellpadding="0" cellspacing="0">
                                    <tbody><tr>
                                        <td>
                                            <table align="center" width="100%" cellpadding="0" cellspacing="0">
                                                <tbody><tr>
                                                    <td align="center" style="padding-bottom:20px;padding-top:25px">
                                                        <a href="" target="_blank">
                                                            <img src="http://zf2.shareplaque/img/logo/logosp160.png" width="" height="" style="border-style:none;vertical-align:top" alt="SharePlaque">
                                                        </a>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td align="center">
                                                        <table width="100%" cellpadding="0" cellspacing="0">
                                                            <tbody><tr valign="top">
                                                                <td style="min-height:1px;border-bottom:1px solid #d7d7d7"></td>
                                                            </tr>
                                                            <tr valign="top">
                                                                <td style="min-height:1px;border-bottom:1px solid #ffffff"></td>
                                                            </tr>
                                                            <tr>
                                                                <td style="padding-left:10px;padding-right:10px;padding-bottom:25px;padding-top:25px">
                                                                    

<table width="100%" cellpadding="0" cellspacing="0">
    <tbody><tr>
        <td style="padding-bottom:15px" align="center">
            <span style="font-family:arial;font-size:16px;font-weight:bold;color:#333333;text-decoration:none">Olá <?php echo $this->dados['nome']; ?>,</span>
        </td>
    </tr>
    <tr>
        <td style="padding-bottom:35px" align="center">
            <span style="font-family:arial;color:#333333;font-size:16px;text-decoration:none;line-height:22px"><?php echo $this->dados['nome_remetente']; ?> precisa cadastrar mais anúncios. Ajude, faça seu cadastro e conheça.</span>
        </td>
    </tr>
    <tr>
        <td align="center" style="padding-bottom:35px">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tbody><tr>
                    <td style="padding-bottom:10px" align="center">
                        <a href="" target="_blank">
                                <img src="<?php echo $this->serverUrl('/img/envelopeInsteadOfThumb-v1.png'); ?>" style="border-style:none;vertical-align:top" width="151" height="134">
                        </a>
                    </td>
                </tr>
                <tr>
                    <td align="center">
                        <a href="" style="font-family:arial;font-size:16px;font-weight:bold;color:#333333;text-decoration:none" target="_blank">
                            <?php echo $this->dados['nome_remetente']; ?>
                        </a>
                    </td>
                </tr>
            
            </tbody></table>
        </td>
    </tr>
    <tr>
        <td align="center" style="padding-bottom:15px">
            <table cellpadding="0" cellspacing="0"><tbody><tr><td bgcolor="#E64372" align="center" style="padding-top:10px;padding-right:25px;padding-bottom:10px;padding-left:25px"><a href="<?php echo $this->serverUrl($this->url('indicado', array('id' => $this->dados['id'],'token' => $this->dados['token']))); ?>" style="font-family:arial;text-decoration:none;font-size:19px;color:#ffffff" target="_blank">Continuar</a></td></tr></tbody></table>
        </td>
    </tr>
</tbody></table>
                                                                 </td>
                                                            </tr>
                                                            <tr valign="top">
                                                                <td style="min-height:1px;border-bottom:1px solid #dcdcdc"></td>
                                                            </tr>
                                                            <tr valign="top">
                                                                <td style="min-height:1px;border-bottom:1px solid #ffffff"></td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            

<table width="100%" cellpadding="0" cellspacing="0">
    <tbody><tr>
        <td style="padding-left:12px;padding-top:17px;padding-bottom:40px;padding-right:12px">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tbody><tr>
                    <td style="text-align:center;padding-bottom:15px">
                        <span style="font-family:arial;font-size:11px;color:#999999;line-height:16px">
                            <a href="mailto:><?php echo $this->dados['email']; ?>" target="_blank"><?php echo $this->dados['email']; ?></a> foi convidado a participar <span class="il">Shareplaque</span> by ><?php echo $this->dados['nome_remetente']; ?>. 
                             Para parar de receber e-mails de <span class="il">SharePlaque</span> <a href="" style="font-family:arial;font-size:11px;color:#666666;text-decoration:none" target="_blank">clique aqui</a>.
                        </span>
                    </td>
                </tr>
                <tr>
                    <td style="text-align:center">
                        <span style="font-family:arial;font-size:11px;color:#999999;line-height:16px">© 2013 <span class="il">SharePlaque</span></span>
                    </td>
                </tr>
            </tbody></table>
        </td>
    </tr>
</tbody></table>
                                        </td>
                                    </tr>
                                </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
        </tbody></table>
        <img src="" width="1" height="1" style="border-style:none;vertical-align:top"><div class="yj6qo"></div><div class="adL">
    </div></div>