<?php 

switch($this->msg['cod_msg']):

  case 1:
    ?> <div class="alert alert-success">Convite enviado com sucesso</div><?php
    break;

  case 2:
    ?> <div class="alert alert-success">Convite reenviado com sucesso</div><?php
    break;
  
endswitch;

$form = $this->form;     
 //$action = $form->get('id')->getValue() ? "edit" : "index" ;
 //$form->setAttribute('action', $this->url('admin/servico',array('action'=>$action)));
 $form->setAttribute('class', 'form-horizontal');
 $form->prepare();
 echo $this->form()->openTag($form) . PHP_EOL;
 //echo $this->formInput($form->get('id'));
// echo $this->formInput($form->get('id_usuario'));
?>
<div class="control-group ">
    <label class="control-label" for="inputEmail">Nome</label>
    <div class="controls">
      <?php echo $this->formInput($form->get('nome')); ?>
      <?php echo $this->formElementErrors($form->get('nome')); ?>
    </div>
  </div>

 <div class="control-group ">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">
      <?php echo $this->formInput($form->get('email')); ?>
      <?php echo $this->formElementErrors($form->get('email')); ?>
    </div>
  </div>
  
  <div class="control-group">
    <div class="controls">
      <button type="button" class="btn" onclick="callAjax('<?php echo $this->url('convite'); ?>',$('#loadconvite'),'POST','nome='+$('#convite').find('input[name=nome]').val()+'&email='+$('#convite').find('input[name=email]').val());">Enviar</button> 
    </div>
  </div>
</form>
			