<h4>Cadastro</h4>
<h5>1º Etapa</h5>
<?php
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
?>

<div class="control-group ">
	<label class="control-label" for="inputEmail">E-mail*</label>
	<div class="controls">
	  <?php echo $this->formInput($form->get('email')); ?>
	  <?php echo $this->formElementErrors($form->get('email')); ?>
	</div>
</div>


<div class="control-group ">
       <?php echo $this->formRow($form->get('captcha')); ?>
</div>

<div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Cadastrar</button> 
    </div>
  </div>
</form>
