<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Shareplaque - Solução em anúncio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/custom.css" rel="stylesheet">
    <link href="/css/jquery.fileupload-ui.css" rel="stylesheet">
    <link href="/js/magiczoomplus/magiczoomplus.css" rel="stylesheet" type="text/css" media="screen"/>
  

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
                                   
   <script src="/js/jquery-1.7.2.min.js"></script>
   <script src="/js/jquery.ui.widget.js"></script>
   <script src="/js/jquery.fileupload.js"></script>
   <script src="/js/magiczoomplus/magiczoomplus.js" type="text/javascript"></script>
   
   
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/"><img src="/img/logo/logosp160.png" /></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <?php $sessionUser = $this->UserIdentity('Login');  if($sessionUser): ?>
              <li class="active"><a href="<?php echo $this->url('meus-anuncios'); ?>">Meus Anúncios</a></li>
              <?php endif; ?>
              <li class=""><a href="<?php echo $this->url('faleconosco'); ?>">Fale Conosco</a></li>
              <li class=""><a href="<?php echo $this->url('faq'); ?>">Faq</a></li>
            </ul>
            
            <ul class="nav pull-right">
              <?php if($sessionUser): ?>
              <li class="">
                <span >Olá,  <?php echo $sessionUser['user']->nome; ?><br><spaN><a href="<?php echo $this->url('conta'); ?>">Editar</a> | <a href="<?php echo $this->url('logout'); ?>">Sair</a></spaN></span>
              </li>
              <?php endif; ?>
            </ul>
             
             
           
            
          </div><!-- .nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    
    
    <?php echo $this->content; ?>
 
      <hr>

      <footer>
        <p>&copy; SharePlaque 2013</p>
      </footer>

    </div> <!-- /container -->
    
    <script src="/js/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap-alert.js"></script>
    <script>
    !function ($) {

      $(function(){

    // tooltip demo
        $('.table').tooltip({
          selector: "a[data-toggle=tooltip]"
        })

    })

    }(window.jQuery)
    </script>
    
  </body>
</html>
