<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Shareplaque ADM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/ui-darkness/jquery-ui-1.10.3.custom.min.css" rel="stylesheet">

    <script src="/js/jquery-1.7.2.min.js"></script>
    <script src="/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/js/globals.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/admin"><img src="/img/logo/logosp160.png" /></a>
          <a class="brand" href="/admin">ADM</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="nav-header">Serviços</li>
                  <li><a href="/admin/servico">Serviços</a></li>
                  <li><a href="/admin/plano">Planos</a></li>
                  <li><a href="<?php echo $this->url('admin/solicitacao-servico'); ?>">Solicitações</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Perguntas</li>
                  <li><a href="<?php echo $this->url('admin/pergunta-denuncia'); ?>">Denuncias</a></li>
                  <li><a href="#"></a></li>
                </ul>
              </li>
              
            </ul>
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    
		
	  <?php echo $this->content; ?>
 
      <hr>

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <script src="/js/bootstrap/bootstrap-transition.js"></script>
    <script src="/js/bootstrap/bootstrap-alert.js"></script>
    <script src="/js/bootstrap/bootstrap-modal.js"></script>
    <script src="/js/bootstrap/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap/bootstrap-scrollspy.js"></script>
    <script src="/js/bootstrap/bootstrap-tab.js"></script>
    <script src="/js/bootstrap/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap/bootstrap-popover.js"></script>
    <script src="/js/bootstrap/bootstrap-button.js"></script>
    <script src="/js/bootstrap/bootstrap-collapse.js"></script>
    <script src="/js/bootstrap/bootstrap-carousel.js"></script>
    <script src="/js/bootstrap/bootstrap-typeahead.js"></script>
    
  </body>
</html>
