<div class="row">
      
        <div class="span9">
          <ul class="breadcrumb">
            <li><a href="/">Home</a> <span class="divider">/</span></li>
            <li><a href="/">Solicitação Serviço</a> <span class="divider">/</span></li>
          </ul>

            <button class="btn btn-mini" type="button" id="btn_filtrar" onclick="displayDivDinamic($('#div_filtra'));">Filtrar</button>
            <div id='div_filtra'>
            <small >
              <table class="">
                <tr>
                  <td>
                    <ul>
                      <li>Id <a href='Javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/list',array('col_order'=>'pa.id','type_order'=>'ASC')); ?>",$("#load-solicitacao-servico"));'><img src="/img/order/gtk-sort-ascending.png" alt="descending, gtk, sort icon"></a> <a href='Javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/list',array('col_order'=>'pa.id','type_order'=>'DESC')); ?>",$("#load-solicitacao-servico"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                      <li>Username <a href='Javascript:callAjax("<?php echo $this->url('list-pergunta-conteudo',array('id_ads'=>$this->ads['id'],'col_order'=>'msg_pergunta','type_order'=>'ASC')); ?>",$("#load-list-pergunta-conteudo"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('list-pergunta-conteudo',array('id_ads'=>$this->ads['id'],'col_order'=>'msg_pergunta','type_order'=>'DESC')); ?>",$("#load-list-pergunta-conteudo"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                      <li>Enviado em <a href='Javascript:callAjax("<?php echo $this->url('list-pergunta-conteudo',array('id_ads'=>$this->ads['id'],'col_order'=>'data_cadastro','type_order'=>'ASC')); ?>",$("#load-list-pergunta-conteudo"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('list-pergunta-conteudo',array('id_ads'=>$this->ads['id'],'col_order'=>'data_cadastro','type_order'=>'DESC')); ?>",$("#load-list-pergunta-conteudo"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                      <li>Status <a href='Javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/list',array('col_order'=>'pa.status','type_order'=>'ASC')); ?>",$("#load-solicitacao-servico"));'><img src="/img/order/gtk-sort-ascending.png" alt=""></a> <a href='Javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/list',array('col_order'=>'pa.status','type_order'=>'DESC')); ?>",$("#load-solicitacao-servico"));'><img src="/img/order/gtk-sort-descending.png" alt=""></a></li>
                    </ul>
                  </td>
                </tr>
              </table>
            </small>
          </div>

          <div id="load-solicitacao-servico">
            
          </div>
        
        </div>

        <div class="span3" id="load-list2">    

        </div>

   
</div>

<script type="text/javascript">
  
!function ($) {

   $(function(){
      $('#div_filtra').hide();
      callAjax("<?php echo $this->url('admin/solicitacao-servico/list',array('col_order'=>'pa.id','type_order'=>'desc')); ?>",$('#load-solicitacao-servico'),null,null,'true');

    })

}(window.jQuery)




</script>