
<table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Divulgar</th>
        <th>Status</th>
        <th>Enviado em</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
      <tr>
        <td><?php echo $value['pa_id']; ?></td>  
        <td>
        <?php
          switch ($value['pa_tipo']) {
            case '1':
              ?>  <a href="<?php echo $this->url("home",array("username"=>$value['u_username'],"action"=>'a',"id_ads"=>$value['pa_id_anuncio'],"url_ads"=>$value['a_url'])); ?>" target="_blank"><?php echo $this->url("home",array("username"=>$value['u_username'],"action"=>'a',"id_ads"=>$value['pa_id_anuncio'],"url_ads"=>$value['a_url'])); ?></a> <?php
              break;
            
            case '2':
             ?> <a href="<?php echo $this->url('home',array('username'=>$value['u_username'])); ?>" target="_blank"><?php echo $this->url('home',array('username'=>$value['u_username'])); ?></a> <?php
              break;  

            case '3':
              ?> <a href="javascript:window.location='<?php echo $value['pa_url_site']; ?>';" target="_blank"><?php echo $value['pa_url_site']; ?></a> <?php
              break;  
            
            default:
              # code...
              break;
          }
        ?>
        </td>
        <td>
        <?php
          switch ($value['pa_status']) {
            case '0':
              ?>  Em análise <?php
              break;
            
            case '1':
             ?>  Divulgado <?php
              break;  

            case '2':
              ?>  Terminado <?php
              break;  
            
            default:
              # code...
              break;
          }
        ?>
        </td>
        <td><?php echo $value['pa_data_cadastro']->format('d/m/Y H:i'); ?></td>
        <td>

          <?php
            switch ($value['pa_status']) {
              case '0':
                ?>  <a href='javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/action',array('action'=>'publica','id_plano_anuncio'=>$value['pa_id'],'id_ads'=>$value['pa_id_anuncio'])); ?>",$("#load-list1"),null,null,null,last_url,$("#load-list1"));' ><i class="icon-edit"></i> Publicar </a> <?php
                break;
              
              case '1':
               ?>  <a href='javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/action',array('action'=>'finalizaservico','id_plano_anuncio'=>$value['pa_id'],'id_ads'=>$value['pa_id_anuncio'])); ?>",$("#load-list2"));' ><i class="icon-remove-circle"></i> Finalizar </a> <?php
                break;  

              case '2':
                ?>   <?php
                break;  
              
              default:
                # code...
                break;
            }
          ?>
            
          </td>
      </tr>
      <?php } }else{ ?>
      <tr>
        <td colspan="5">Nenhum pergunta enviada</td>
      </tr>
      
      <?php } ?>
        </tbody>
  </table>
  <?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>
  <script type="text/javascript">

     !function ($) {
    
         $(function(){

              // tooltip demo
              $('.table').tooltip({
                selector: "a[data-toggle=tooltip]"
              });

        })
    
    }(window.jQuery)

</script>        
