
<table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Pergunta</th>
        <th>Enviado em</th>
        <th>Status</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
      <tr>
        <td><?php echo $value->id; ?></td>  
        <td width="65%"><?php echo $value->msg_pergunta; echo "<br><br>"; echo $value->msg_resposta; ?></td>
        <td><?php echo $value->data_cadastro->format('d/m/Y H:i'); ?>
        </td>
        <td>

        
        <?php
          switch ($value->status) {
            case '0':
              $src= "/img/status/status_mod.png";
              $txt_tooltip= "aguardando resposta";
              break;

            case '1':
              $src= "/img/status/status_ok.png";
              $txt_tooltip= "publicada";
              break;
            
            case '2':
              $src= "/img/status/status_rep.png";
              $txt_tooltip= "retirada do anúncio";
              break;  

            case '4':
              $src= "/img/status/status_rep.png";
              $txt_tooltip= "removida por denuncia";
              break;  
            
            default:
              # code...
              break;
          }
        ?>
         <a href="#" data-toggle="tooltip" data-placement="top" data-original-title="Pergunta <?php echo $txt_tooltip; ?>"><img src="<?php echo $src; ?>" /></a>
        </td>
        <td>
          <?php if($value->status == 1): ?>
            <a href='javascript:callAjax("<?php echo $this->url('admin/pergunta-denuncia/action',array('id_ads'=>$value->id_anuncio,'action'=>'remove','id_pergunta'=>$value->id)); ?>",$("#load-list-pergunta-denuncia"),null,null,null,last_url,$("#load-list-pergunta-denuncia"));' ><i class="icon-remove-circle"></i> Retirar </a>
            <?php elseif($value->status == 4): ?>
            <a href='javascript:callAjax("<?php echo $this->url('admin/pergunta-denuncia/action',array('id_ads'=>$value->id_anuncio,'action'=>'publica','id_pergunta'=>$value->id)); ?>",$("#load-list-pergunta-denuncia"),null,null,null,last_url,$("#load-list-pergunta-denuncia"));' ><i class="icon-edit"></i> Publicar </a>
            <?php endif; ?>

          </td>
      </tr>
      <?php } }else{ ?>
      <tr>
        <td colspan="5">Nenhum pergunta enviada</td>
      </tr>
      
      <?php } ?>
        </tbody>
  </table>
  <?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>
  <script type="text/javascript">

     !function ($) {
    
         $(function(){

              // tooltip demo
              $('.table').tooltip({
                selector: "a[data-toggle=tooltip]"
              });

        })
    
    }(window.jQuery)

</script>        
