
<table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Divulgar</th>
        <th>Status</th>
        <th>Status Ads</th>
        <th>Enviado em</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
      <tr>
        <td><?php echo $value['u_username']; ?></td>
        <td>
        <?php
          switch ($value['pa_tipo']) {
            case '1':
              ?>  <a href="<?php echo $this->url("home",array("username"=>$value['u_username'],"action"=>'a',"id_ads"=>$value['pa_id_anuncio'],"url_ads"=>$value['a_url'])); ?>" target="_blank"><?php echo $this->url("home",array("username"=>$value['u_username'],"action"=>'a',"id_ads"=>$value['pa_id_anuncio'],"url_ads"=>$value['a_url'])); ?></a> <?php
              break;
            
            case '2':
             ?> <a href="<?php echo $this->url('home',array('username'=>$value['u_username'])); ?>" target="_blank"><?php echo $this->url('home',array('username'=>$value['u_username'])); ?></a> <?php
              break;  

            case '3':
              ?> <a href="javascript:window.location='<?php echo $value['pa_url_site']; ?>';" target="_blank"><?php echo $value['pa_url_site']; ?></a> <?php
              break;  
            
            default:
              # code...
              break;
          }
        ?>
        </td>
        <td>
        <?php
          switch ($value['pa_status']) {
            case '0':
              ?>  Em análise <?php
              break;
            
            case '1':
             ?>  Publicado <?php
              break;  

            case '2':
              ?>  Finalizado <?php
              break;  
            
            default:
              # code...
              break;
          }
        ?>
        </td>
        <td>
        <?php
          switch ($value['a_status']) {
            case '0':
              ?>  Em Moderação <?php
              break;
            
            case '1':
             ?>  Aprovado <?php
              break;  

            case '2':
              ?>  Reprovado <?php
              break;

            case '3':
              ?>  Desativado <?php
              break;

            case '4':
              ?>  Removido <?php
              break;  
            
            default:
              # code...
              break;
          }
        ?>
        </td>
        <td><?php echo $value['pa_data_cadastro']->format('d/m/Y H:i'); ?></td>
        <td>

          <?php
            switch ($value['pa_status']) {
              case '0':
                ?>  <a href='javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/action',array('action'=>'publica','id_plano_anuncio'=>$value['pa_id'],'id_ads'=>$value['pa_id_anuncio'])); ?>",$("#load-solicitacao-servico"),null,null,null,last_url,$("#load-solicitacao-servico"));' ><i class="icon-edit"></i> Publicar </a> <?php
                break;
              
              case '1':
               ?>  <a href='javascript:callAjax("<?php echo $this->url('admin/solicitacao-servico/action',array('action'=>'finalizaservico','id_plano_anuncio'=>$value['pa_id'],'id_ads'=>$value['pa_id_anuncio'])); ?>",$("#load-list2"));' ><i class="icon-remove-circle"></i> Finalizar </a> <?php
                break;  

              case '2':
                ?> <i class="icon-remove-circle"></i> Histório   <?php
                break;  
              
              default:
                # code...
                break;
            }
          ?>
            
          </td>
      </tr>
      <?php if($value['pa_status'] == 2){ ?>

       <tr>
           <td colspan="5">
            <small>
              <?php echo 'Data inicio: '.$value['pa_data_inicio']->format('d/m/Y').' / Data fim: '.$value['pa_data_fim']->format('d/m/Y')." / Média clique: ".$value['pa_media_clique']." / posicao média: ".$value['pa_posicao_media']." / Impressões: ".$value['pa_impressao']; ?>
            </small>
           </td>
       </tr>

      <?php } } }else{ ?>
      <tr>
        <td colspan="5">Nenhum pergunta enviada</td>
      </tr>
      
      <?php } ?>
        </tbody>
  </table>
  <?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>
  <script type="text/javascript">

     !function ($) {
    
         $(function(){

              // tooltip demo
              $('.table').tooltip({
                selector: "a[data-toggle=tooltip]"
              });

        })
    
    }(window.jQuery)

</script>        
