<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {

            $ar_uri = explode("/",$urlPattern);
            $key_page = array_search('page', $ar_uri);
            
            if(empty($key_page)){
                $ar_uri[count($ar_uri)] = "page";
                $ar_uri[count($ar_uri)+1] = $page;
            }else{
            $ar_uri[$key_page+1] = $page;
            }
            return implode("/", $ar_uri);
            /*if (!preg_match('/page/', $urlPattern))
                return $urlPattern . "/page/" . $page;
            else
                return preg_replace('/\d/', $page, $urlPattern);*/
        };

$ar_url = explode("/", $urlPattern);
        //echo $formatUrl(2);
?>
<center>
<?php if ($this->pageCount): ?>
        <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> registro(s)
            <br />


            <!-- First page link -->
    <?php if (isset($this->previous)): ?>
                <a href='Javascript:callAjax("<?php echo $formatUrl($this->first) ?>",$("#load-<?php echo $ar_url[2]; ?>"),null,null,"true");'>
                    Primeira
                </a> |
    <?php else: ?>
                <span class="disabled">Primeira</span> |
            <?php endif; ?>


            <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
                <a href='Javascript:callAjax("<?php echo $formatUrl($this->previous) ?>",$("#load-<?php echo $ar_url[2]; ?>"),null,null,"true");'>
                    < Anterior
                </a> |
    <?php else: ?>
                <span class="disabled">< Anterior</span> |
            <?php endif; ?>


            <!-- Next page link -->
    <?php if (isset($this->next)): ?>
                <a href='Javascript:callAjax("<?php echo $formatUrl($this->next) ?>",$("#load-<?php echo $ar_url[2]; ?>"),null,null,"true");'>
                    Próximo >
                </a> |
    <?php else: ?>
                <span class="disabled">Próximo ></span> |
            <?php endif; ?>


            <!-- Last page link -->
    <?php if (isset($this->next)): ?>
                <a href='Javascript:callAjax("<?php echo $formatUrl($this->last) ?>",$("#load-<?php echo $ar_url[2]; ?>"),null,null,"true");'>
                    Último
                </a>
    <?php else: ?>
                <span class="disabled">Último</span>
            <?php endif; ?>

        </div>

<?php endif; ?>
</center>