<div class="row">
        
        <div class="span7">

          <ul class="breadcrumb">
          <li><a href="/">Home</a> <span class="divider">/</span></li>
          <li class="active">Faq</li>
        </ul>        
        
          <h4>Faq (Perguntas Frequentes)</h4>

          <p><b>1 - Sou novo usuário, como faço para se cadastrar no site?</b></p>
          <p>Na home, clique no link "Cadastre-se Grátis". Digite seu e-mail e clique em cadastrar</p>


            
        </div>
   
</div>
