    <?php

switch($this->msg):

  case 1:
    ?> <div class="alert alert-success">Foi enviado um email para sua conta confirmando a alteração da senha!</div><?php
    break;
  
  
  case 2:
    ?> <div class="alert alert-success">Você não confirmou seu email, reenviamos novamente um email para confirmação.</div><?php
    break;
  
endswitch;
?>
<h4>Recuperar senha</h4>
<p>
Preencha os campos abaixo e você receberá uma mensagem com um link, que lhe permitirá redefinir sua senha.
</p>
<?php
$form = $this->form;
//$form->setAttribute('class', 'form-horizontal');
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form) . PHP_EOL;
//echo $this->formHidden($form->get('id')) . PHP_EOL;
?>

<div class="control-group ">
  <label class="control-label" for="inputEmail">E-mail*</label>
  <div class="controls">
    <?php echo $this->formInput($form->get('email')); ?>
    <?php echo $this->formElementErrors($form->get('email')); ?>
  </div>
</div>


<div class="control-group ">
     <div class="controls">
       <?php echo $this->formRow($form->get('captcha')); ?>
       </div>
</div>

<div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Enviar</button> 
    </div>
  </div>
</form>