<div class="row">
  
    <div class="span7">
        <ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url("meus-anuncios"); ?>">Meus Anúncios</a> <span class="divider">/</span></li>
    <li class="active"><a href="<?php echo $this->url("home",array('username'=>$this->dados['username'])); ?>"><i class="icon-user"></i> <?php echo $this->dados['username']; ?></a></li>
  </ul> 

    	<?php if(!empty($this->dados['collections_images'])): foreach($this->dados['collections_images'] as $item): ?>
        	<a href="<?php echo $item['full']; ?>" class="MagicZoomPlus" rel="hint:false; expand-effect:back; group:effects; zoom-position:top; caption-source:img:alt; expand-speed:1200;"><img src="<?php echo $item['50']; ?>" alt="<?php echo $this->dados['titulo']; ?>"/></a>
    	<?php endforeach; endif;?>
        <h3><?php echo $this->dados['titulo']; ?></h3>
        <p><?php echo $this->dados['descricao']; ?></p>

        <fieldset>
            <legend><i class="icon-list"></i> Perguntas</legend>
            <div id="load-listperguntapublica">
            </div>
        </fieldset>
    </div>
    <div class="span5" id="load-pergunta-publica">    

    </div>
</div>
<script type="text/javascript">
  
!function ($) {

   $(function(){

      callAjax("<?php echo $this->url('pergunta-publica',array('id_ads'=>$this->dados['id_ads'])); ?>",$('#load-pergunta-publica'));

      callAjax("<?php echo $this->url('list-pergunta-publica',array('id_ads'=>$this->dados['id_ads'],'col_order'=>'data_resposta','type_order'=>'DESC')); ?>",$('#load-listperguntapublica'));

    })

}(window.jQuery)




</script>

