
          
<table class="table-pergunta-publica">
  <thead>
    <tr>
      <td>#</td>
      <td>Título</td>
    </tr>
  </thead>
  <tbody>
  	<?php if(!empty($this->dados)) { foreach ($this->dados as $key => $value) { ?>
    <tr>
      <td width="5%"><?php echo $value->id; ?></td>
      <td><a href="<?php echo $this->url("home",array("username"=>$this->username,"action"=>'a',"id_ads"=>$value->id,"url_ads"=>$value->url)); ?>" data-toggle="tooltip" data-original-title="Visualizar Anúncio"><?php echo $value->titulo; ?></a></td>
    </tr>
    <tr>
      <td width="5%"></td>
      <td><?php echo substr($value->descricao,0,50)."..."; ?></td>
    </tr>
    <tr>
      <td width="5%"></td>
      <td id="loadfotos<?php echo $value->id; ?>">
<script>callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage','id'=>$value->id,'cod'=>1)); ?>",$('#loadfotos<?php echo $value->id; ?>'));</script>
      </td>
    </tr>
    <?php } }else{ ?>
    <tr>
    	<td colspan="4">Nenhum anúncio cadastro</td>
    </tr>
    
    <?php } ?>
  </tbody>
</table>
<?php echo $this->paginationControl($this->dados,'Sliding','paginator'); ?>

      <script type="text/javascript">
      

      	
		 !function ($) {
		
		     $(function(){

		     		//callAjax("<?php echo $this->url('convite'); ?>",$('#loadconvite'));
					
				    $('.fileupload').fileupload({
				        // Uncomment the following to send cross-domain cookies:
				        //xhrFields: {withCredentials: true},
				        url: $(this).attr('action'),
				        autoupload: true,
				        add: function (e, data) {
				        	//console.dir(data);
				        	//console.dir(data.files);
				        	var valid = true;
	                        var re = /^.+\.((jpg)|(png)|(gif)|(jpeg))$/i;
	                        var form_current = $(this); 
	                        
	                        form_current.find('.loading').html("<img src='/img/loading/loading.gif' />");
				            
	                        $.each(data.files, function (index, file) {
	                        	if (!re.test(file.name)) {
	                            	form_current.find('.loading').html("");
			                        $('.alert').find('span').html('This file type is not supported');
			                        $('.alert').show();
	                                valid = false;
	                            }
	                        });
	                        if (valid)
	                            data.submit();
				        	
				        },
	                    done: function (e, data) {
	                    	var obj = JSON.parse(data.result);
	                        $(this).find('.loading').html("");
	                        if(obj.files.error != undefined){
	                        	
	                        	$('.alert').find('span').html(obj.files.error);
	                        	$('.alert').show();
	                        	//$('.alert').alert();
	                        }else{
	                        	callAjax("<?php echo $this->url("meus-anuncios",array('action'=>'displayimage')); ?>/"+obj.files[0].id,$('#loadfotos'+obj.files[0].id));
	                        }	
	                        
	                    },
	                    error: function () {
	                        $(this).find('.label-important').html('An error occured while uploading the document.');
	                    }
				    });
		
		    })
		
		}(window.jQuery)
		

		

      </script>





